### PR TITLE
Fix for default and override locale setting

### PR DESCRIPTION
**Pull request by JamesSmartCell**
This PR fixes a few issues noticed with the locale settings, which has become a bit messy after a few re-edits.

Issues: 

1. When phone was switched to a different locale (without user explicitly choosing a locale from the settings), the phone wouldn't always pick up the changed locale.
2. Text in some menus didn't appear in the locale language on restarting the app.
3. Duplicated code.
4. Some translations were missed (see values-zh/strings.xml)

While editing the relevant classes, cleanup of redundant code was also done.

Code was checked on Pixel, Xiaomi and Huawei phones set to different locales. To repeat a check:

1. Create new emulator instance.
2. Set device language to Chinese or Spanish
3. Install AW - text should appear in the device language.
4. Change language - should be in the override language.
5. Restart app, setting should persist.
Bonus: Check the top right hamburger menu in DappBrowser; previously text was in English no matter what language settings were applied.

### CODE REVIEW

**Review by James-Sangalli — CHANGES_REQUESTED** [review]
@JamesSmartCell if you kill the app it resets back to English, otherwise it works as expected.

**Comment by JamesSmartCell** [comment]
> @JamesSmartCell if you kill the app it resets back to English, otherwise it works as expected.

Unable to reproduce. Can you describe how to reproduce in more detail?

**Comment by James-Sangalli** [comment]
> > @JamesSmartCell if you kill the app it resets back to English, otherwise it works as expected.
> 
> Unable to reproduce. Can you describe how to reproduce in more detail?

On the emu I change the language, kill the app and then reopen it.

I expect it to be in the changed language but it reverts back to English instead

**Comment by JamesSmartCell** [comment]
@James-Sangalli fresh install or old version it works correctly for me on all test phones. How about I give you a build, perhaps there was a build issue. I rebased too. I'll be preparing a release candidate today, so you can test that.

**Comment by JamesSmartCell** [comment]
Here is a new build; please check if it works on your device as expected:

https://drive.google.com/file/d/17j28cRWduOGHqSydPK7ieHtVhZ4YljPe/view?usp=sharing

**Comment by JamesSmartCell** [comment]
Merging this PR as verified correctly.

**Pull request merged**
