### PR TITLE
Hide function bar if Wallet type is WATCH

### LINKED ISSUE #951: able to get to transaction confirmation page with erc721/erc875 assets in watch account

### PR DESCRIPTION
**Pull request by ChintanRathod**
Fixes #951

### CODE REVIEW

**Comment by ChintanRathod** [comment]
Tested with 2 approaches, 1) Watch 2) Import and output is like below. 
If WATCH account, Function buttons will be hidden
If IMPORT one, functions buttons will be visible

ezgif com-optimize

**Comment by JamesSmartCell** [comment]
Thanks! Can you add this feature: If it's a watch wallet, but we're using a debug build then expose the buttons but indicate the reason why with a 'DEBUG'.

See the code here (from erc20activity)

```
        if (BuildConfig.DEBUG || wallet.type != WalletType.WATCH)
        {
            functionBar = findViewById(R.id.layoutButtons);
            functionBar.setupFunctions(this, viewModel.getAssetDefinitionService(), token, null, null);
            functionBar.revealButtons();

            if (BuildConfig.DEBUG && wallet.type == WalletType.WATCH)
            {
                findViewById(R.id.text_debug).setVisibility(View.VISIBLE);
            }
        }
```

and also the layout from the 2020/06 schema:

```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:background="@color/colorPrimary"
    android:orientation="vertical"
    android:paddingStart="12dp"
    android:paddingEnd="12dp"
    android:paddingBottom="12dp"
    android:visibility="visible">

    <LinearLayout
        android:layout_width="wrap_content"
        android:layout_height="12dp"
        android:background="@color/colorPrimary"
        android:orientation="horizontal">

        <TextView
            android:id="@+id/text_debug"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:textColor="@color/dark_seed_danger"
            android:layout_marginStart="2dp"
            android:layout_marginBottom="1dp"
            android:text="DEBUG"
            android:textSize="10sp"
            android:visibility="gone"/>

    </LinearLayout>

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="horizontal"
        android:visibility="visible">

        <Button
            android:id="@+id/primary_button"
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            android:layout_marginLeft="4dp"
            android:layout_marginRight="4dp"
            android:layout_weight="0.5"
            android:background="@drawable/selector_round_button"
            android:ellipsize="end"
            android:fontFamily="@font/font_semibold"
            android:lines="1"
            android:paddingLeft="5dp"
            android:paddingRight="5dp"
            android:text="Primary"
            android:textAllCaps="false"
            android:textColor="@color/white"
            android:textSize="17sp"
            android:visibility="gone" />

        <Button
            android:id="@+id/secondary_button"
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            android:layout_marginLeft="4dp"
            android:layout_marginRight="4dp"
            android:layout_weight="0.5"
            android:background="@drawable/selector_round_button_secondary"
            android:ellipsize="end"
            android:fontFamily="@font/font_semibold"
            android:lines="1"
            android:text="Secondary"
            android:textAllCaps="false"
            android:textColor="@drawable/selector_button_text_secondary"
            android:textSize="17sp"
            android:visibility="gone" />

        <ImageButton
            android:id="@+id/more_button"
            android:layout_width="0dp"
            android:layout_height="48dp"
            android:layout_marginLeft="4dp"
            android:layout_marginRight="4dp"
            android:layout_weight="0.2"
            android:background="@drawable/selector_round_button_secondary"
            android:drawableTint="@color/azure"
            android:gravity="center"
            android:src="@drawable/ic_menu_azure"
            android:tint="@drawable/selector_button_text_secondary"
            android:visibility="gone" />
    </LinearLayout>
</LinearLayout>
```

**Comment by JamesSmartCell** [comment]
The layout change shown above is now in master

**Comment by ChintanRathod** [comment]
@JamesSmartCell I understand. I will change the code as it is stated in "Erc20DetailActivity". 
- Will check for the DEBUG build, setup function buttons
- Also if DEBUG, add a text on top for indication

**Comment by JamesSmartCell** [comment]
@ChintanRathod you'll have to re-branch from current master and modify the two changed files again - only need to update TokenFunctionActivity and it's ViewModel.

Not sure what happened here, probably due to two big branch merges.

**Comment by ChintanRathod** [comment]
Closing as many merge issues on PR after rebase.

**Pull request closed without merging**
