### PR TITLE
TokenScript Command line tool

### PR DESCRIPTION
**Pull request by JamesSmartCell**
New project - commandline tool for TokenScript showing minimal reference implementation of TS.

TODO:
- check ERC20 scripts.
- check certificate validity (can be built-in).
- check actions.
- allow calling of actions.
- allow pushing to TS actions given a key.

### CODE REVIEW

**Comment by James-Sangalli** [comment]
Closes #927

**Comment by James-Sangalli** [comment]
@colourful-land bump

**Comment by colourful-land** [comment]
I will process this one right after today's Thursday meeting.

**Comment by colourful-land** [comment]
It builds fine:

````
$ gradle fatjar

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.0/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 2s
3 actionable tasks: 1 executed, 2 up-to-date
````

Then it doesn't run:

````
$ java -jar build/libs/scripttool-all-1.0.jar 
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.SecurityException: Invalid signature file digest for Manifest main attributes
	at sun.security.util.SignatureFileVerifier.processImpl(SignatureFileVerifier.java:330)
	at sun.security.util.SignatureFileVerifier.process(SignatureFileVerifier.java:263)
	at java.util.jar.JarVerifier.processEntry(JarVerifier.java:275)
	at java.util.jar.JarVerifier.update(JarVerifier.java:230)
	at java.util.jar.JarFile.initializeVerifier(JarFile.java:383)
	at java.util.jar.JarFile.ensureInitialization(JarFile.java:612)
	at java.util.jar.JavaUtilJarAccessImpl.ensureInitialization(JavaUtilJarAccessImpl.java:69)
	at sun.misc.URLClassPath$JarLoader$2.getManifest(URLClassPath.java:991)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:451)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)
````

**Comment by colourful-land** [comment]
build failed on Travis because it failed to download dependency from maven repository server which gives 403 on legit packages.

**Pull request merged**
