### PR TITLE
Implemented wallet naming feature (#1795)

### PR DESCRIPTION
**Pull request by mpaschenko**

### CODE REVIEW

**Comment by JamesSmartCell** [comment]
Hi @mpaschenko looks good so far, can you action the two points from the linked issue then it'll be good to merge.

**Comment by JamesSmartCell** [comment]
Hi @mpaschenko it works great I like this method of doing it.

Can you add in these things:

- Implement IME for soft keyboard in the 'Name This Wallet' Activity; if you click the tick it should be the same as pressing 'Save Name'.
- Show the current name in the 'Change / Add Wallet' Activity (```class WalletsActivity```)

_AlphaWallet

See in the picture the ENS name in the top wallet - If I rename this wallet, the preferred name should show. Same with other wallets.

**Review by JamesSmartCell — CHANGES_REQUESTED** [review]
See the attached comment

**Comment by JamesSmartCell** [comment]
Hi @mpaschenko one last thing; can you add the new strings to all 4 language xmls (strings - already there, zh/strings, es/strings, fr/strings). Add in English, these periodically get translated. When you add the string, a dialog will allow you to tick zh/es/fr and the default strings.

**Comment by mpaschenko** [comment]
@JamesSmartCell added translations as you requested

**Review by JamesSmartCell — APPROVED** [review]

**Pull request merged**
