### PR TITLE
Deeplinks for Android 12

### PR DESCRIPTION
**Pull request by JamesSmartCell**
Android 12 introduces a similar model to Apple deeplinks for security and spoofing resistance.

In order for a website to open an app we now need an ```assetlinks.json``` file accessible from the root of the website, similar to what iOS requires.

This file contains the fingerprint of the signing key and the application ID of the app that can be opened when this website is called from any browser.

### CODE REVIEW

**Comment by weiwu-zhang** [comment]
````
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
Caused by: java.lang.RuntimeException: org.xml.sax.SAXException: Sequence must be enclosed within <namedType name=... />
	at com.alphawallet.token.web.AppSiteController.addContractAddresses(AppSiteController.java:442)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
	at com.alphawallet.token.web.AppSiteController.main(AppSiteController.java:403)
	... 8 more
Caused by: org.xml.sax.SAXException: Sequence must be enclosed within <namedType name=... />
	at com.alphawallet.token.tools.TokenDefinition.handleModule(TokenDefinition.java:1023)
	at com.alphawallet.token.tools.TokenDefinition.handleAddresses(TokenDefinition.java:989)
	at com.alphawallet.token.tools.TokenDefinition.extractTags(TokenDefinition.java:420)
	at com.alphawallet.token.tools.TokenDefinition.parseTags(TokenDefinition.java:898)
	at com.alphawallet.token.tools.TokenDefinition.<init>(TokenDefinition.java:391)
	at com.alphawallet.token.web.AppSiteController.addContractAddresses(AppSiteController.java:437)
	... 22 more
````

**Review by weiwu-zhang — CHANGES_REQUESTED** [review]
I know it tested working for you @JamesSmartCell but I still hope to get rid of the error shown.

**Comment by JamesSmartCell** [comment]
I don't see this when I test. Does it also occur if you try to build DMZ from the current master?

**Comment by weiwu-zhang** [comment]
> I don't see this when I test. Does it also occur if you try to build DMZ from the current master?

No. this error occurred when running the jar file you provided @JamesSmartCell

**Comment by weiwu-zhang** [comment]
I reproduced this error locally with my laptop, using the dmz.jar file downloaded from @JamesSmartCell 

````
$ /home/weiwu/.jdks/azul-15.0.5/bin/java -Dsun.misc.URLClassPath.disableJarChecking=true -jar ~/Descargas/dmz.jar --server.ssl.key-store=/etc/ssl/ec2-dmz.p12 --server.ssl.key-store-password=ChipRulzCBA2017 --server.port=1443 --repository.dir=IdeaProjects/TokenScript-Repo/

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.2.2.RELEASE)

2022-04-10 21:55:46.926  INFO 5922 --- [           main] c.a.token.web.AppSiteController          : Starting AppSiteController on pure with PID 5922 (/home/weiwu/Descargas/dmz.jar started by weiwu in /home/weiwu)
2022-04-10 21:55:46.928  INFO 5922 --- [           main] c.a.token.web.AppSiteController          : No active profile set, falling back to default profiles: default
2022-04-10 21:55:47.809  INFO 5922 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 1443 (https)
2022-04-10 21:55:47.817  INFO 5922 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2022-04-10 21:55:47.817  INFO 5922 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.29]
2022-04-10 21:55:47.867  INFO 5922 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2022-04-10 21:55:47.868  INFO 5922 --- [           main] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 874 ms
2022-04-10 21:55:48.077  INFO 5922 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2022-04-10 21:55:48.460  INFO 5922 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 1443 (https) with context path ''
2022-04-10 21:55:48.462  INFO 5922 --- [           main] c.a.token.web.AppSiteController          : Started AppSiteController in 1.902 seconds (JVM running for 2.344)
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
Caused by: java.lang.RuntimeException: org.xml.sax.SAXException: Sequence must be enclosed within <namedType name=... />
	at com.alphawallet.token.web.AppSiteController.addContractAddresses(AppSiteController.java:442)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at com.alphawallet.token.web.AppSiteController.main(AppSiteController.java:403)
	... 8 more
Caused by: org.xml.sax.SAXException: Sequence must be enclosed within <namedType name=... />
	at com.alphawallet.token.tools.TokenDefinition.handleModule(TokenDefinition.java:1023)
	at com.alphawallet.token.tools.TokenDefinition.handleAddresses(TokenDefinition.java:989)
	at com.alphawallet.token.tools.TokenDefinition.extractTags(TokenDefinition.java:420)
	at com.alphawallet.token.tools.TokenDefinition.parseTags(TokenDefinition.java:898)
	at com.alphawallet.token.tools.TokenDefinition.<init>(TokenDefinition.java:391)
	at com.alphawallet.token.web.AppSiteController.addContractAddresses(AppSiteController.java:437)
	... 22 more
^C2022-04-10 21:55:53.481  INFO 5922 --- [extShutdownHook] o.s.s.concurrent.ThreadPoolTaskExecutor  : Shutting down ExecutorService 'applicationTaskExecutor'
````

**Comment by JamesSmartCell** [comment]
maybe it needs to be reformatted. I'll try again

**Comment by seabornlee** [comment]
This may fix #2411 . I will test it.

**Comment by seabornlee** [comment]
> This may fix #2411 . I will test it.

Still not working.

**Comment by JamesSmartCell** [comment]
> > This may fix #2411 . I will test it.
> 
> Still not working.

This is exactly what the fix is for - we need to update the server before it will work

**Comment by JamesSmartCell** [comment]
Closes #2411 - confirmed with release build.

**Pull request merged**
