### PR TITLE
Add `Rootstock` Network

### PR DESCRIPTION
**Pull request by ahsan-javaiid**
### Description
This PR adds [rootstock](rootstock.io) network to the list of available networks. 
- Using ethereum derivation path
- Send / Receive RBTC working using public node
- Market value using coingecko
- Tx history using blockscout api

### Demo
Screenshot 2023-05-30 at 6 24 52 PM

### Demo Video

https://github.com/AlphaWallet/alpha-wallet-android/assets/104683677/805b603b-dd52-4683-bfa0-cce259a3e008

### CODE REVIEW

**Comment by ahsan-javaiid** [comment]
cc: @alepc253

**Comment by JamesSmartCell** [comment]
Hi @ahsan-javaiid thank you for this excellent PR - I can't see any issue here. I have one suggestion (yes I know!): our users like to have access to the testnet. I see there is a testnet on chainId 31. Since we always add the testnet if it exists would you be able to include this too?

**Comment by ahsan-javaiid** [comment]
I think good idea! I will add testnet and update the pull request!. Thanks for the suggestion. 👍

**Comment by JamesSmartCell** [comment]
Just a sidenote - we usually use the same SVG icon for testnet as mainnet but colour it with #B2C6D8
Eg see ic_icons_tokens_mumbai.xml vs ic_icons_polygon.xml.

**Review by JamesSmartCell — APPROVED** [review]

**Pull request merged**
