### PR TITLE
Update with constraint layout

### LINKED ISSUE #1351: Use adaptive layout for 'Redeem' activity.
Currently Redeem layout crushes the TokenScript view on certain smaller sized phone displays.

Convert the view to an adaptive one so that smaller phones still display correctly. See attached picture from Pixel 1st gen. Maybe use ConstraintLayout to build a relative view.

The relevant activity is RedeemSignatureDisplayActivity.

1a39c1ce-4504-4dc2-af3c-e2aa9decdb75

### PR DESCRIPTION
**Pull request by ChintanRathod**
Fixes #1351

### CODE REVIEW

**Comment by ChintanRathod** [comment]
Output is like below. Kindly review and revert if it is as expected. I didn't work on QR code resize as it won't make too much difference except Top padding and Bottom padding. 

scrolling screen

**Comment by JamesSmartCell** [comment]
Is it possible to have the view re-size the token instead? Scroll is not a good solution in this case.

**Comment by JamesSmartCell** [comment]
OK it may not be possible to scale the webview. Try this: If the screen is detected to be smaller then don't display the 'present the to redeem ...' (can't remember the exact phrase, but the text that appears at the top of the screen below the title), only display the QR code at the top, then the token at the bottom of the screen - could use RelativeLayout, although ConstraintLayout would be better.

**Comment by ChintanRathod** [comment]
@JamesSmartCell Replaced existing view with Constraint layout as suggested. Output is like below in Pixel 1. 

image

**Pull request merged**
