### PR TITLE
[Swap] Improve search filter on SelectTokenDialog

### PR DESCRIPTION
**Pull request by justindg**
Added a slight improvement to user experience when searching through the token list. With this change, the filtered list prioritizes entries that **starts with** the search filter, THEN all other entries containing the filter

For example, if your search filter is `ETH`, the token `Ethereum (ETH)` will most likely be on top of the list (if combined with changes from #2724).

### CODE REVIEW

**Review by seabornlee — CHANGES_REQUESTED** [review]
Suggest eliminating duplications.
Pass `data.symbol` & `data.name` into a `match()` method.

**Comment by justindg** [comment]
@seabornlee The TokenFilter class looks good, I'll check back to test if the filter works as desired.

**Comment by justindg** [comment]
I modified the filter to achieve the desired order. To demonstrate further, here is an example of a simple search with keyword `ETH`

1) Double filter - ETH shows up first, which is more than likely what the user wants
292546601_600088614831823_3261977048091429420_n

2) Single filter:
293255745_564589131976857_3873232521465638742_n

**Review by JamesSmartCell — APPROVED** [review]

**Comment by seabornlee** [comment]
> @seabornlee The TokenFilter class looks good, I'll check back to test if the filter works as desired.

Oh, sorry I didn't realize the order is critical. To express the intention, you can write a unit test other than add comments since unit tests can encourage refactoring.

**Comment by seabornlee** [comment]
image

**Comment by justindg** [comment]
> @justindg My result looks different than yours.

Have to update with latest master (the other PR included alphabetical sorting)

**Comment by seabornlee** [comment]
> > @justindg My result looks different than yours.
> 
> Updated with latest master (the other PR included alphabetical sorting of the initial list)
Ok, thx!

**Review by seabornlee — APPROVED** [review]

**Pull request merged**
