### PR TITLE
Migrated ViewPager to ViewPager2

### PR DESCRIPTION
**Pull request by asif-finimble**
Closes: #2218

### CODE REVIEW

**Review by JamesSmartCell — CHANGES_REQUESTED** [review]
Please avoid using numbers in your variable/object names; we do sometimes use numbers at the end of the variable/object names but this is for when we are replacing a legacy class; once the legacy class has been removed the number would be removed.

Eg: GasService2 was in place for a while while GasService was being deprecated.

**Comment by asif-finimble** [comment]
Merged master and resolved conflicts.

**Comment by JamesSmartCell** [comment]
@asif-finimble Expected merge conflict from your fragment fix

**Comment by asif-finimble** [comment]
@JamesSmartCell the conflicts are resolved.

**Review by JamesSmartCell — APPROVED** [review]

**Pull request merged**
