### PR TITLE
Fix for Euro Input

### PR DESCRIPTION
**Pull request by JamesSmartCell**
Fixes an issue with entering European mainland style input (eg 100,00).

Also refactor and optimise the ENS check (issue seen in the posted video): No need to check for ENS if input cannot be ENS.

https://user-images.githubusercontent.com/12689544/111546455-d2391800-87cb-11eb-8e07-5c2bc0e4add9.mp4

### CODE REVIEW

**Review by colourful-land — CHANGES_REQUESTED** [review]
What's the reason to use home-grown parser instead of [DecimalFormat.parse()](https://developer.android.com/reference/java/text/DecimalFormat)?

**Review by colourful-land — CHANGES_REQUESTED** [review]
Please don't convert Number into double! You risk getting 0.9999999 out of 1

**Comment by JamesSmartCell** [comment]
Then can you just re-code the routine to how you think it should be and I can take it from there? I checked StackOverflow for what people do for actual production code and my original routine is closest to what is the go.

**Comment by colourful-land** [comment]
> Then can you just re-code the routine to how you think it should be and I can take it from there? I checked StackOverflow for what people do for actual production code and my original routine is closest to what is the go.

Happy to do that but can you correct this:

> The default Locale is constructed statically at runtime for your application process from the system property settings, so it will represent the Locale selected on that device when the application was launched. Typically, this is fine, but it does mean that if the user changes their Locale in settings (system or in-app) after your application process is running, the value of getDefaultLocale() probably will not be immediately updated.

**Review by colourful-land — APPROVED** [review]
looks good

**Pull request merged**
