### PR TITLE
Convert Network Selection Dialog to Activity

### PR DESCRIPTION
**Pull request by justindg**
#513

### CODE REVIEW

**Comment by JamesSmartCell** [comment]
Apologies for the long delay in checking.

The new activity does look better and means there's no need for scrolling to see all the options (at least on high res phones). Need to double check it scrolls correctly on a lower resolution phone. Would be great to have the selections colour coded like metamask:

networkselect

However the network selection on dapp browser should still be a dialog box, with a title 'Select Network'. The difference is that you're selecting a single network rather than choosing a filter. It can be an activity, but this doesn't make sense for the UX.

**Comment by colourful-land** [comment]
@James-Sangalli 

1. Why is this approved when the ask is to make it into an activity and it ended up still a dialogue?

@justindg 

2. If this is about the pop up in dapp browser, Please don't show the networks not enabled in Settings, instead, tell the users to enable more network in Settings.

**Comment by colourful-land** [comment]
@justindg 
it should 𝑛𝑜𝑡 be possible for the user to choose a network not previously enabled in Settings when the user browses a dapp, no matter how much convenience it brings, even if the browser can correctly identify the user should be accessing a network not previously enabled in Settings.

If you prioritize consitency, you get convenice. If you priorize convenience, you get neither consistency nor convenience.

**Comment by colourful-land** [comment]
I would approve if this is done @JamesSmartCell 

1. Only list the enabled networks in the dialogue.
2. Hint that more networks are available in settings (yes, I know a message is not the best design)
3. The word "Ethereum" is made into a button, with a browser "refresh" icon followed by the text "Ethereum".

**Comment by JamesSmartCell** [comment]
Just to reduce confusion: the spec @justindg was following was to convert all dialog into activity, and the previous operation of the network picker in dapp browser didn't restrict based on network filters.

Ok I have a design solution for the button; pending a redesign which fulfils the requirement. 

I'll update the PR.

**Comment by James-Sangalli** [comment]
> @James-Sangalli
> 
> 1. Why is this approved when the ask is to make it into an activity and it ended up still a dialogue?
> 
> @justindg
> 
> 1. If this is about the pop up in dapp browser, Please don't show the networks not enabled in Settings, instead, tell the users to enable more network in Settings.

It is not a dialog, it is an activity.

**Comment by JamesSmartCell** [comment]
It makes sense for the filters to be a separate activity but not for the network selector in dappbrowser.

**Comment by colourful-land** [comment]
> It is not a dialog, it is an activity.

@James-Sangalli When you gave justing https://github.com/AlphaWallet/alpha-wallet-android/issues/513 do you mean:

𝑎) the network selector in Settings should be changed to an activity;
𝑏) the network selector in dapp should be changed to an activity;

I think Justin took your intention as 𝑎+𝑏 when you only intended 𝑎

I can't remember well but I must have lacked precision and was laconic too in my first start-up. It takes time to build that skill but I think the short cut is to speak verbosely at the outset and learn to make it terse later.

**Comment by James-Sangalli** [comment]
> #513

The issue clearly says that it should be an activity, also, this issue was created long before network filters were made as it was done in Jan, before we had the multi chain UI.

The network selection page should still be an activity like this PR addressed.

**Comment by JamesSmartCell** [comment]
With the UX overhaul it now makes sense for network select to be an activity. Will merge after testing.

**Comment by colourful-land** [comment]
> The network selection page should still be an activity like this PR addressed.

Which is the selection page?

𝑎) the network filter in Settings 
𝑏) the network selector in dapp

**Comment by James-Sangalli** [comment]
@JamesSmartCell Please remember to delete the branch and close the issue

**Pull request merged**
