### PR TITLE
Implement Task #722

### PR DESCRIPTION
**Pull request by ChintanRathod**
- Add code to clean browser cache and show message to the user

### CODE REVIEW

**Comment by justindg** [comment]
Hi @ChintanRathod, I think the requirement is to clear the cache of the Web3View in DappBrowserFragment? 

@tomekalphawallet would you require a dialog for user confirmation before clearing the cache?

**Comment by ChintanRathod** [comment]
@justindg I understand, but Web3View is ultimately using WebView as base and it has all implementation. Please check [this link](https://developer.android.com/reference/android/webkit/WebView.html#clearCache%28boolean%29) which defines if WebView cache directory is wiped, it's associated all instance data will be wiped because of single location cache mechanism used by Android OS.

**Comment by JamesSmartCell** [comment]
I'll have to check it but if it works it's a clever solution!

**Comment by JamesSmartCell** [comment]
@ChintanRathod please add me as reviewer on pull requests

**Comment by justindg** [comment]
> @justindg I understand, but Web3View is ultimately using WebView as base and it has all implementation. Please check [this link](https://developer.android.com/reference/android/webkit/WebView.html#clearCache%28boolean%29) which defines if WebView cache directory is wiped, it's associated all instance data will be wiped because of single location cache mechanism used by Android OS.
> 
> As defined in supporting document of Google, it is not necessary to clear the cache at used instance. We can wipe anywhere in the application as cache used by WebView is common per application basis.

Never knew this, this is brilliant!

**Comment by ChintanRathod** [comment]
@JamesSmartCell, please review this. 
@justindg Thank you :)

**Pull request merged**
