### PR TITLE
Add Levinswap to dapps_list

### PR DESCRIPTION
**Pull request by LucaSilverhand**
Add Levinswap to dapps_list

### CODE REVIEW

**Comment by JamesSmartCell** [comment]
Hi @LucaSilverhand, thank you for adding your dapp.

If you like, we can also add your dapp to our wallet front page (the one you see when you start AlphaWallet) into one of the categories. If we do this, would it be possible for you to list us on your dapp page?

**Comment by LucaSilverhand** [comment]
Hey James

I'm on board. One question: do you mean on DEX interface or landing page? (new landing is in works)

**Comment by JamesSmartCell** [comment]
Hi Lucas, great, we'll get you added in. As to where to list us, we'll leave that to you - landing page somewhere is good though :)

@colourfreak can you add Levinswap under exchange?

**Comment by LucaSilverhand** [comment]
Can we get added to "xDai" section as well?

**Comment by colourfreak** [comment]
@LucaSilverhand Do you have a logo in .svg format?

**Comment by colourfreak** [comment]
https://wiki.levinswap.org/assets - Found it!

**Comment by colourfreak** [comment]
Added.

**Pull request merged**
