### PR TITLE
Rework Wallets Page to accommodate wallet names

### PR DESCRIPTION
**Pull request by justindg**
Here are the details of the rework:
- Wallet can now have names
- **Export** and **Delete** has been removed from the Wallets screen, replaced by **More** button
- **More** button takes the user to a new **Wallet Actions** screen, where user can rename, delete, backup wallet

 @farrahfazirah - Would love to hear feedback for the UX. Feel free to give recommendations to improve it

### CODE REVIEW

**Comment by James-Sangalli** [comment]
@justindg please rebase commits

**Comment by JamesSmartCell** [comment]
We tried rebase but merge conflicts appeared. So, this will go through as is so not to endanger code quality.

**Comment by James-Sangalli** [comment]
@JamesSmartCell @justindg please see my other PR here #627 to see if this rebase is ok. We should use it over this one if so.

**Comment by JamesSmartCell** [comment]
Extra work was required after testing, so this is still the valid branch

**Comment by justindg** [comment]
@James-Sangalli I used rebase on this branch yesterday when there were new commits from master - hence the force push from the log. I'm not seeing merge commits from the log so I assume it worked properly, would you be able to verify? :)

**Comment by James-Sangalli** [comment]
@justindg looks correct but you can also squash some of your extra commits which are incomplete e.g. WIP commits or fix commits can be squashed into one feature

**Comment by JamesSmartCell** [comment]
@justindg are you going to rebase it here?

**Pull request merged**
