### PR TITLE
add French to locales in class LocaleRepository

### PR DESCRIPTION
**Pull request by desouzag**
Added French to locales in class LocaleRepository

### CODE REVIEW

**Comment by JamesSmartCell** [comment]
Hi @desouzag, thankyou for committing this PR :) The Travis build error is indicating there's unescaped apostrophes, so eg in this line:

```<string name="body_low_gas">Gas price is set below the 'slow\' speed.\nYour transaction may take a long time to be written or may never be written.</string>```

It needs to be like this:

```<string name="body_low_gas">Gas price is set below the \'slow\' speed.\nYour transaction may take a long time to be written or may never be written.</string>```

Likewise, anywhere where the ```'``` character is used in the strings.xml file, it must be escaped with the ```\``` character.

**Comment by desouzag** [comment]
Hello @JamesSmartCell , thank you. 

I'll update it and submit again.

**Comment by JamesSmartCell** [comment]
Hi @desouzag do you have any update on the translations yet?

**Comment by desouzag** [comment]
Hi @JamesSmartCell, I was sick all week. I will be able to publish an update by the end of next week. I am almost finish, 200 lines more or less.

**Pull request closed without merging**
