### PR TITLE
Fix SwapProvider NPE

### LINKED ISSUE #2916: Crash: SwapProviderAdapter.java line 66
image

### PR DESCRIPTION
**Pull request by seabornlee**
Close #2916

### CODE REVIEW

**Review by JamesSmartCell — CHANGES_REQUESTED** [review]
@seabornlee I think this will fail formatting checks

**Comment by seabornlee** [comment]
> @seabornlee I think this will fail formatting checks

Let me rebase and see.

**Review by justindg — APPROVED** [review]

**Comment by JamesSmartCell** [comment]
Check the brace formatting near the 'No Swap Providers found.' message.

**Comment by seabornlee** [comment]
> Check the brace formatting near the 'No Swap Providers found.' message.

Thanks James. I will figure out why the checker didn't spot this.

**Comment by seabornlee** [comment]
By reading source code of editorConfigChecker, just realized it only support basic EditorConfig rules, not including Java/C or other language specific rules.
Will find another alternative later.

**Pull request merged**
