### PR TITLE
Added 'X' button in QR Scanner.

### LINKED ISSUE #2403: Can't go back from Camera. Camera should have a X/cancel button
Should have a top bar with a X/cancel button like this:

Screenshot 2022-02-10 at 11 40 11 AM

https://app.zeplin.io/project/5d088205bff2d15de6a4397b/screen/5e6f647f9d20081669e6748d

### PR DESCRIPTION
**Pull request by asif-finimble**
Closes #2403

### CODE REVIEW

**Comment by asif-finimble** [comment]
Ok. I'll update the strings usage. As for the "ic_close", I used it but it was shown in white color and thus not visible in the toolbar. Therefor I created new one from the default vector icons provided by MaterialDesign.

**Comment by JamesSmartCell** [comment]
If I change it to ic_close it shows as black to me. It's used in the ActionSheetDialog and also appears black there. Could this be a theme-ing issue? Essentially the 'x' you checked in and the 'x' for ic_close are identical data except for sizing (same colour etc). Can you try it again and see if ic_close is indeed white?

Also - I don't mind if, when you create a new class you add your header to the top of the file (in fact, yep that's cool) but please remove your header from the inside of source files, it distracts from the source code maintenance. It's already clear who wrote it from the github logs.

Thanks,

James

**Comment by justindg** [comment]
Just want to add - in the upcoming dark mode patch, the toolbar icon colors will be fixed. I created new styles that will help with consistency. It might be better not to add new assets. I'll edit these files anyway once it's merged to master :)

**Comment by JamesSmartCell** [comment]
> Just want to add - in the upcoming dark mode patch, the toolbar icon colors will be fixed. I created new styles that will help with consistency. It might be better not to add new assets. I'll edit these files anyway once it's merged to master :)

So, go with ic_close to ensure it works with the dark mode.

**Comment by asif-finimble** [comment]
I noticed a weird thing. If I use ```ic_close``` then sometimes it shows black and sometimes it shows white. After adding ```tint``` in the vector, its working correctly now.

**Comment by JamesSmartCell** [comment]
Now it has broken the ActionSheetDialog 'x' which is now white Just leave it as is, and let's let @justindg's re-themeing fix this.

**Comment by JamesSmartCell** [comment]
@asif-finimble bump

**Comment by asif-finimble** [comment]
@JamesSmartCell, I have restored the ic_close to original. Can be merged now.

**Review by JamesSmartCell — APPROVED** [review]

**Pull request merged**
