### PR TITLE
Use Amberdata API

### PR DESCRIPTION
**Pull request by JamesSmartCell**
Use Amberdata API as primary data source. This allows us to add tickers for ERC20 tokens that have a presence in the Amberdata market price database.

### CODE REVIEW

**Comment by JamesSmartCell** [comment]
I sent you a PM about where to get the private API key.

**Comment by JamesSmartCell** [comment]
Still it demonstrates the fallback pricing which is obtained from the DAI oracle works fine, in case both the APIs are down.

**Comment by James-Sangalli** [comment]
@JamesSmartCell closes https://github.com/AlphaWallet/alpha-wallet-android/issues/903?

**Comment by JamesSmartCell** [comment]
good catch.
Fixes #903 .

**Pull request merged**
