### PR TITLE
Update transaction details

### LINKED ISSUE #1377: Add copy-to-clipboard button to Transaction Details
Visual (by Tomek, if in question, ask him)
https://app.zeplin.io/project/5d0356be2f25b319dcc5944b/dashboard?seid=5e170e6ef7b0f25419ad8e00

iOS: https://github.com/AlphaWallet/alpha-wallet-ios/issues/1792

### PR DESCRIPTION
**Pull request by ChintanRathod**
Fixes #1377

### CODE REVIEW

**Comment by ChintanRathod** [comment]
@JamesSmartCell Output of this change is as below. 

ezgif com-video-to-gif

**Comment by JamesSmartCell** [comment]
Is it possible to fit without needing to add scroll?

**Comment by tomekalphawallet** [comment]
@ChintanRathod You can have a floating button (sticked to the bottom).

**Comment by JamesSmartCell** [comment]
Now there's a floating button scroll is fine

**Comment by ChintanRathod** [comment]
Output after feedback changes 

ezgif com-video-to-gif (3)

**Pull request merged**
