### PR TITLE
- Implemented non zero block testnet list in WalletsActivity when use…

### PR DESCRIPTION
**Pull request by keval-finimble**
Added horizontal list of blockchains in WalletsActivity to show case the non zero blocks when testnet is active.

### CODE REVIEW

**Comment by seabornlee** [comment]
hi @keval-finimble , pls check the lint errors and Unit test job which is failed.

**Comment by JamesSmartCell** [comment]
> hi @keval-finimble , pls check the lint errors and Unit test job which failed.

**Comment by JamesSmartCell** [comment]
> > hi @keval-finimble , pls check the lint errors and Unit test job which failed.

re-open, accidentally closed

**Comment by JamesSmartCell** [comment]
@keval-finimble can you check the source commit I just made and all the //TODO - JB comments. You can make the code quite a bit more simple by checking those.

Also you may want to simplify that error handler with the nested if statements, you can could check if you can chuck custom errors and handle those in their own methods.

**Pull request closed without merging**
