### PR TITLE
Fix for sendUncheckedTransaction freeze issue

### LINKED ISSUE #846: EtherJS signer.sendUncheckedTransaction freezes with Alpha Wallet on Android
https://github.com/ethers-io/ethers.js/issues/603
@ethereumgeek

### PR DESCRIPTION
**Pull request by JamesSmartCell**
Fixes #846. Callback was using incorrect return type and not actually passing any data.

### CODE REVIEW

**Comment by hboon** [comment]
@JamesSmartCell is this something that might affect iOS?

**Comment by JamesSmartCell** [comment]
@hboon, yes it does but you may have already implemented it correctly. When you send a transaction formatted from a dapp you'll first go to the confirmation page to confirm. On return from the confirmation page you need to complete the callback in JS - that is in ```init.js```:

```
executeCallback(callbackId, null, hash)
```

You can confirm if iOS is working correctly by using the page provided here: https://ethersjs.web.app

Set dapp browser to rinkeby and click on the ```clicking here``` hyper link. After return from confirmation page the ```not started``` text should change to ```has hash``` then after it's written to a block it'll change to ```has receipt```. If you don't return the correct type in the callback you'll see ```has error``` and if you don't return the callback you'll see ```prompt user```. 


Note that for a transaction return the last param is the transaction hash, not the signature.

**Comment by hboon** [comment]
@JamesSmartCell do you have screenshots of what should happen? I tried MetaMask, Trust wallet, Opera Touch and they all failed the test.

**Comment by JamesSmartCell** [comment]
I think they threw this sample together for us to test, I had to reload a few times, keep clicking on the 'clicking here' hyperlink until you get the confirmation page then you should be good

**Comment by JamesSmartCell** [comment]
It's possible you need to do the login first. The exact sequence I did was also to test metamask, I got an eth from the faucet, logging in in the process. Then it should work with that account

**Comment by hboon** [comment]
@JamesSmartCell ah, thanks. It works in iOS already. The trick like you said is to create an account and login first to reproduce it properly.

**Pull request merged**
