### PR TITLE
Update dapps_list.json

### PR DESCRIPTION
**Pull request by emmanbol**
Tbull token added

### CODE REVIEW

**Comment by JamesSmartCell** [comment]
> Tbull token added

Hi @emmanbol , thank you for adding your dapp.

If you like, we can also add your dapp to our wallet front page (the one you see when you start AlphaWallet) into one of the categories. If we do this, would it be possible for you to list us on your dapp page?

**Comment by emmanbol** [comment]
That will be fine.

**Comment by JamesSmartCell** [comment]
@colourfreak can you add the tbull utility dapp to our 'Utility' section. The text description is "A Utility Token on Binance Smart Chain for Payments for Services".

Cheers!

**Review by JamesSmartCell — APPROVED** [review]

**Comment by colourfreak** [comment]
> Tbull token added

Do you have a token logo in .svg format?

**Pull request merged**
