### PR TITLE
Implement Task #1136

### PR DESCRIPTION
**Pull request by ChintanRathod**
- Add 6 (USD, EUR, GBP, AUD, CNY, INR) currencies at initial level to select from setting screen
- Add initial selection of USD and later user can select own default currency from the list
- Stored selection to local preference
- Change TickerService to apply changed currency to wallet display

### CODE REVIEW

**Comment by JamesSmartCell** [comment]
Hi @ChintanRathod . This looks great.

Could I ask for just two small mods though.

First - the currency icons should be round; can you use the ones that @tomekalphawallet posted above - you may need to tweak them when you import but I think the import feature on Android Studio generates rounded icons.

Second - your resume method in HomeActivity - can it call the progress spinner in WalletFragment so the user knows something is being updated (```systemView.showProgress(true);```)? Then, when the ticker update completes the currency update and calls refreshTokens() in WalletFragment it can switch the progressSpinner off ```systemView.showProgress(false);```

**Comment by ChintanRathod** [comment]
@JamesSmartCell Thanks for sparing time to review the PR and sharing feedback. I will check and update the code accordingly. I will check for the rounded icons. If I faced any issue, will let you know to have some help from @tomekalphawallet.

**Comment by ChintanRathod** [comment]
@JamesSmartCell As per instructed, implemented first modification of circular icon with newer design proposed by @tomekalphawallet. The second modification was not able to implemented due to some new widget integration into home activity.
Would you please review the additional changes and let me know if need any change.

**Comment by JamesSmartCell** [comment]
Great, we can now add new currencies in a few seconds.
The spinner issue wasn't as clear cut as I thought due to some legacy code confusing the issue. I tidied this up.

**Pull request merged**
