### PR TITLE
implemented setup of the price alerts (only ui at the moment) #2257

### LINKED ISSUE #2257: Implement Price Alerts
See https://app.zeplin.io/project/5d088205bff2d15de6a4397b/dashboard?tag=Samoa

image

Add the views for creating price alerts (using InputAmount widget), and swipe out/delete.

### PR DESCRIPTION
**Pull request by mpaschenko**
Closes #2257

### CODE REVIEW

**Comment by JamesSmartCell** [comment]
@mpaschenko can you re-point this at the master branch, I have now merged the Samoa update

**Comment by mpaschenko** [comment]
Hi @JamesSmartCell updated branch to include price alert notification service, please take a look

**Comment by JamesSmartCell** [comment]
> Hi @JamesSmartCell updated branch to include price alert notification service, please take a look

Wow this is awesome! Nice work.

**Comment by seabornlee** [comment]
@mpaschenko Are you still working on this? Is there any blocker? Looks like not updated for 20 days.

**Comment by JamesSmartCell** [comment]
We're going to have to merge/rebase this PR with master; I tried and there's a lot of conflicts. I can perform the merge later as most of the conflicts appear to be minor.

**Comment by seabornlee** [comment]
Too many conflicts, close this and send another.

**Pull request closed without merging**
