### PR TITLE
Migrated Dagger-Android to Dagger-Hilt v2.40.5

### PR DESCRIPTION
**Pull request by asif-finimble**
Closes: #2321

### CODE REVIEW

**Review by JamesSmartCell — CHANGES_REQUESTED** [review]
@asif-finimble please resolve the merge conflict - since you began some modifications have happened; you'll need to convert the new view models to the new injection style.

**Comment by asif-finimble** [comment]
Merged master and updated injection code.

**Comment by JamesSmartCell** [comment]
@asif-finimble sorry, requires merging after the Timber PR! Will wait for this before pushing any other PR.

**Comment by asif-finimble** [comment]
> @asif-finimble sorry, requires merging after the Timber PR! Will wait for this before pushing any other PR.

No problem. will merge and push update

**Comment by JamesSmartCell** [comment]
Looks like we're really close to closing this one, it almost works perfectly, I got this crash earlier:

```
2022-02-04 09:20:04.641 17460-17460/io.stormbird.wallet E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.stormbird.wallet, PID: 17460
    java.lang.IllegalStateException: onAttach called multiple times with different Context! Hilt Fragments should not be retained.
        at dagger.hilt.internal.Preconditions.checkState(Preconditions.java:83)
        at com.alphawallet.app.ui.Hilt_BaseFragment.onAttach(Hilt_BaseFragment.java:58)
        at com.alphawallet.app.ui.Hilt_TokenInfoFragment.onAttach(Hilt_TokenInfoFragment.java:41)
        at androidx.fragment.app.Fragment.onAttach(Fragment.java:1783)
        at com.alphawallet.app.ui.Hilt_BaseFragment.onAttach(Hilt_BaseFragment.java:47)
        at com.alphawallet.app.ui.Hilt_TokenInfoFragment.onAttach(Hilt_TokenInfoFragment.java:31)
        at androidx.fragment.app.Fragment.performAttach(Fragment.java:2922)
        at androidx.fragment.app.FragmentStateManager.attach(FragmentStateManager.java:464)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:275)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
        at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1971)
        at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:311)
        at androidx.fragment.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:249)
        at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1244)
        at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1092)
        at androidx.viewpager.widget.ViewPager.onMeasure(ViewPager.java:1622)
        at android.view.View.measure(View.java:25156)
        at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
        at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
        at android.view.View.measure(View.java:25156)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7109)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:145)
        at android.view.View.measure(View.java:25156)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7109)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1580)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:849)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:728)
        at android.view.View.measure(View.java:25156)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7109)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:25156)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7109)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1580)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:849)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:728)
        at android.view.View.measure(View.java:25156)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7109)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:1103)
        at android.view.View.measure(View.java:25156)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3669)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2294)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2691)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2166)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8884)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1280)
        at android.view.Choreographer.doCallbacks(Choreographer.java:1019)
        at android.view.Choreographer.doFrame(Choreographer.java:911)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1248)
        at android.os.Handler.handleCallback(Handler.java:900)
        at android.os.Handler.dispatchMessage(Handler.java:103)
2022-02-04 09:20:04.641 17460-17460/io.stormbird.wallet E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8668)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
```

It's repeatable; try the following:

1. Go to settings, add wallet, and watch 'vitalik.eth'.
2. Back to main wallet page and wait for the sync to start showing assets
3. Once you see the tokens like ERC20, OMG Network, MoonRabbit etc, click on any one of these.
4. Change the graph dates a couple of times (may not be necessary).
5. Back to wallet
6. Click on a different token, it should crash as above.

It looks fairly straightforward to fix.

**Comment by asif-finimble** [comment]
@JamesSmartCell Apparently the crash is caused because the fragments are created in ```DetailPages``` enum and enums are not garbage collected so the fragments stay in memory due to which the same fragment instance is reused for different tokens. I have fixed it by creating a class ```DetailPage``` and creating new instances of fragments.

**Review by JamesSmartCell — APPROVED** [review]

**Pull request merged**
