### PR TITLE
Overhaul Theming System (Dark Mode Support)

### LINKED ISSUE #2366: Update BarButton's primary and secondary colors
- [x] #2367
- [x] #2368

### LINKED ISSUE #2367: Replace the primary button color "green" to "cod"
Cod #141414

https://zpl.io/V1gGYrk
https://zpl.io/p1rxRoJ

Screenshot 2022-01-28 at 16 13 51

### LINKED ISSUE #2368: Replace the secondary button color
We need to change the outline color of secondary buttons from "Azure" to "Cod" #141414

https://zpl.io/b6pdYeR
https://zpl.io/bemE75m
https://zpl.io/p1rxRoJ
Screenshot 2022-01-28 at 16 16 41

### LINKED ISSUE #2369: Add Dark Mode
There are several rules which we have to follow, for quicker implementation
I will try to describe it as much as I can.

Dove #727272 to Dusty #999999
Azure #007fed to Dodge #0c84ff
White #ffffff bg to Cod #141414
Green remains the same
Alabaster #fbfbfb to Venus #232323
Mercury #e9e9e9 to Venus #232323
Mine #2f2f2f to White #ffffff

Dark mode:
https://zpl.io/09kMrOm
Activity-Send-Opened-ETH-Dark
Backup-Write-Down
ETH-Activity
ETH-Alert
ETH-Info
Import-Keystore-Password-Empty-Dark
My-Wallet-Address
Send-ETH-Confirm-Dark
Send-ETH-Illustration-Dark
Send-ETH-Recipient-Entered
Settings-Backup-Warning-Dark
Settings-Dark
Settings-Support
Wallet-Dark
Wallet-Summary-Dark
Welcome-Dark
Activity-Dark

### LINKED ISSUE #2447: Update Android App Icon
hdpi
mdpi
play
xhdpi
xxhdpi
xxxhdpi

### PR DESCRIPTION
**Pull request by justindg**
- Closes #2369 
- Closes #2368 
- Closes #2367 
- Closes #2366 
- Closes #2447 

--
## Patch Summary
With the introduction of dark mode, this is the perfect opportunity to overhaul AlphaWallet's theming and styling system. These changes allow developers to efficiently build new layouts and allow for customization and rebranding.

* **New Theming and Styling system** - Changed the way components/views are built by introducing standard themes, styles, and values
* **Implemented Dark Mode** - App can now switch between Light, Dark, and Auto (System) modes
* **Cleaned up unused resources** - Removed unused and redundant drawables, layouts and values
* **Cleaned up most layouts** - Refactored components to use new theming system
* **Consolidated resources that can be used** - ex. minimize the amount of toolbars for easier maintenance
* **Fixed UI bugs** - Adjusted alignments, inefficient layouts, etc.
* **Apply new logo and launcher icon**

## Theming
Android themes define default values for colors and styles through references. Native components inherit their default attributes from the theme. For instance:
* The **status bar**'s default background color is derived from `?colorPrimaryDark`
* The activated color for framework controls (ie. **Switch** or **CheckBox**) is derived from `?colorControlActivated`.

In the new theming system (via `@style/AppTheme`), the default values for (1) color references and (2) common native component styles are overriden, which means only minimal interference is needed to style a view. For example, the default `switchStyle` is `@style/Aw.Component.Switch`. No need to specify branding colors.

#### Color references
Using color references (ex. `colorPrimary`, `colorSurface`, etc) is the preferred way of applying colors to your on to your view, style or drawable. By doing so, we allow flexibility to apply theme overlays over specific layouts of the app. 

Example: 
```xml
    <style name="Aw.Typography.Title">
        <item name="android:textSize">@dimen/sp20</item>
        <item name="android:textColor">?android:textColorPrimary</item>
    </style>
```

#### Theme overlays
Some components may be required to display a specific theme, no matter if the app is in dark or light mode. For example, the `Backup Warning Notification` buttons are always in dark mode, so we simply apply `android:theme="@styleAppTheme.DarkOverlay"` to it's parent layout.

> More info is available in `theming.md`

## Styling
Prior to this patch, there is no standard way of building most views. For instance, each view is styled with a specific color or text size repeatedly across different files. 

Consider this example of creating a simple label:
```xml
    <TextView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:fontFamily="font_regular"
        android:textColor="@color/dove"
        android:textSize="15sp" 
        ... />
```

There are a few undesirable things in this scenario:
* The component is not descriptive
* Developers have to manually specify all the attributes every time
* The color does not allow flexibility - it will still be `dove` in dark mode
* If the overall app theme (think Fiji or Samoa upgrade) is changed, developers have to manually find and change all instances of this view

#### The new styling system
The goal is to make components (1) consistent, (2) easy to build, and (3) flexible for theme changes. With that said, I have reviewed the entire code in order to create a stanndard set of styles for the most common components, which you will find under `values/styles.xml` and `values/typography.xml`.

With the new styling system, here is the updated way of creating a label:
```xml
    <TextView
        style="@style/Aw.Typography.Label"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        ... />
```

The attributes of `@style/Aw.Typography.Label` are defined in `values/typography.xml`:
```xml
    <style name="Aw.Typography.Label">
        <!-- inherited from Aw.Typography -->
        <!-- <item name="android:fontFamily">@font/font_regular</item> -->
        <item name="android:textSize">@dimen/sp15</item>
        <item name="android:textColor">?android:textColorSecondary</item>
    </style>
```
> Tip: If you want to change all the labels across the app, simply change the values defined in this style.

##### Colors
While it is highly discouraged to directly apply these colors to your views or styles, it is important to understand how these files are utilized in the app.
* **`colors.xml`** - Maps the values for color references in the app theme (ex. `@color/brand` = `@color/azure`). The dark mode equivalent values are located at `night/colors.xml` (ex. `@color/brand` = `@color/dodge`)
* **`palette.xml`** - Defines the app branding colors with the actual hexadecimal value (ex. `@color/azure` = `#007fed`).

#### Dimens
This patch makes full use of the standard spacing values defined in Zeplin.
* **`dimens.xml`** - Defines standard spacing values (ex. `standard_16` = `16dp`)

#### Support for smaller screen sizes
By using `dp` and `sp` values, the Android framework attempts to display every layout as similar as possible across different screen sizes.

In the event that a specific value or style is needed to support a different sized screen, add the resource under the appropriate `values-xxx` folder (ex. `values-w320dp` for screens with a 320dp width).

## Final notes
It will take some time to get used to the new system, but doing so will allow us to create efficient workflows as the app grows. Also check out `theming.md`, which is included in the repo for more information and examples.

### CODE REVIEW

**Comment by JamesSmartCell** [comment]
@justindg wow really nice. 

I notice you also normalised all code style (something I like to see). It would be logical to commit the .idea file (or whatever it may be called) so auto-formatting is correct for all further work. Can you see to this?

**Review by JamesSmartCell — CHANGES_REQUESTED** [review]
Only found one issue; be in light mode, click on the main menu on wallet page, then 'show my wallet address'. CopyViewText widget doesn't display correctly.

**Comment by justindg** [comment]
> Only found one issue; be in light mode, click on the main menu on wallet page, then 'show my wallet address'. CopyViewText widget doesn't display correctly.

Solved in the latest commit! 💯

**Review by JamesSmartCell — APPROVED** [review]
Looks good!

**Pull request merged**
