### PR TITLE
Fix auto download

### PR DESCRIPTION
**Pull request by JamesSmartCell**
Fix for auto download file location (for Chinese users mainly), plus fix the resource leak observed from time to time if the server can't find the location.

### CODE REVIEW

**Comment by colourful-land** [comment]
Hi. The CCP uses something called random forest and it might hold the connection for an undetermined amount of time even if the apk is not in blacklist if the user wins some lottery. Can you tell me whether or not that piece of code would freeze the app should that happen?

**Comment by JamesSmartCell** [comment]
2000 ms timeout for establishing connection.

**Comment by James-Sangalli** [comment]
@colourful-land on you to merge this PR once your concerns are met.

**Comment by JamesSmartCell** [comment]
Also, the thread runs in the background, so it doesn't hold up wallet startup.

**Pull request merged**
