### PR TITLE
Replaced Log.x, System.out.println & e.printStacktrace with Timber.x

### LINKED ISSUE #2395: Convert remaining Log.d to Timber.log
eg in  `checkTokensBalance` in `TokensService`.

### PR DESCRIPTION
**Pull request by asif-finimble**
Closes #2395

### CODE REVIEW

**Comment by asif-finimble** [comment]
@JamesSmartCell I have put this PR on hold. can merge this once #2384 is merged else we'll get conflicts.

**Comment by asif-finimble** [comment]
@JamesSmartCell will resolve conflicts for this once #2383 is merged as we may get more conflicts.

**Comment by JamesSmartCell** [comment]
@asif-finimble This can be completed now

**Comment by asif-finimble** [comment]
@JamesSmartCell, This can be merge now. Conflicts Resolved.

**Comment by JamesSmartCell** [comment]
Sorry @asif-finimble the big NFT refactor produced some merge conflicts. This PR *WILL* be next once resolved again!

thanks,

James

**Comment by asif-finimble** [comment]
@JamesSmartCell this can be merged now. Conflicts resolved.

**Review by JamesSmartCell — APPROVED** [review]

**Pull request merged**
