### PR TITLE
Avoid TokenListHolder bind tokenIcon crash

### LINKED ISSUE #2643: Crashes: java.lang.NullPointerException com.alphawallet.app.entity.tokens.Token.getName
image
image

```
java.lang.NullPointerException: 
  at com.alphawallet.app.entity.tokens.Token.getName (Token.java:226)
  at com.alphawallet.app.entity.tokens.Token.getName (Token.java:220)
  at com.alphawallet.app.widget.TokenIcon.bindData (TokenIcon.java:146)
  at com.alphawallet.app.ui.widget.holder.TokenListHolder.bind (TokenListHolder.java:72)
  at com.alphawallet.app.ui.widget.holder.TokenListHolder.bind (TokenListHolder.java:22)
  at com.alphawallet.app.ui.widget.adapter.TokenListAdapter.onBindViewHolder (TokenListAdapter.java:276)
  at com.alphawallet.app.ui.widget.adapter.TokenListAdapter.onBindViewHolder (TokenListAdapter.java:52)
  at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder (RecyclerView.java:7254)
  at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder (RecyclerView.java:7337)
  at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline (RecyclerView.java:6194)
  at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline (RecyclerView.java:6460)
  at androidx.recyclerview.widget.GapWorker.prefetchPositionWithDeadline (GapWorker.java:288)
  at androidx.recyclerview.widget.GapWorker.flushTaskWithDeadline (GapWorker.java:345)
  at androidx.recyclerview.widget.GapWorker.flushTasksWithDeadline (GapWorker.java:361)
  at androidx.recyclerview.widget.GapWorker.prefetch (GapWorker.java:368)
  at androidx.recyclerview.widget.GapWorker.run (GapWorker.java:399)
  at android.os.Handler.handleCallback (Handler.java:883)
  at android.os.Handler.dispatchMessage (Handler.java:100)
  at android.os.Looper.loop (Looper.java:224)
  at android.app.ActivityThread.main (ActivityThread.java:7562)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:539)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:950)
```

### PR DESCRIPTION
**Pull request by asif-finimble**
Fixes #2643 

Not able to reproduce the bug. Added exception handler to avoid app crash

### CODE REVIEW

**Review by JamesSmartCell — CHANGES_REQUESTED** [review]
Let's also fix the get name issue so that when the token with null name comes, something will be displayed (blank circle perhaps, or icon if it's there).

**Comment by asif-finimble** [comment]
> Let's also fix the get name issue so that when the token with null name comes, something will be displayed (blank circle perhaps, or icon if it's there).

@JamesSmartCell the getName is going to be called by bindData which we have just try-catched. or do we need to change it elsewhere?

**Comment by JamesSmartCell** [comment]
try-catching it is only masking the issue, but it's a good idea as it won't be a big fail.

**Comment by JamesSmartCell** [comment]
@asif-finimble I didn't really like this fix as the root bug could still happen elsewhere (possibly), so I traced the logic issue to the root like this: #2701

**Comment by asif-finimble** [comment]
@JamesSmartCell yes the root bug was still pending to be solved. Its a great fix. Thanks.

**Pull request closed without merging**
