### PR TITLE
e2e test and activity test

### LINKED ISSUE #2042: Implement RoboElectric (or other framework)
Check the RoboElectic testing harness: http://robolectric.org/

What we want to do is, via gradle tests, run a test script that adds a watch wallet (you can try 0xC067A53c91258ba513059919E03B81CF93f57Ac7 to start with) then visits each page in the settings screen.

Once it's set up a further issue will expand this to check some tokens and later import a private key and do sends.

The initial stage should just run the app and open the various pages. We can test the wallet name too, as you can get the title and check it has resolved the ENS name which should be jsbrown.eth

### PR DESCRIPTION
**Pull request by seabornlee**
Resolve #2042

Tasks:

- [x] e2e: change settings
- [x] e2e: transfer from A account to B account
1. Import a wallet (just create a new wallet and store the seed phrase, or create a new wallet in MetaMask and export the raw key).
2. Check the address of the wallet
3. Move some testnet balance onto this wallet (any testnet is fine, Ropsten is easy to get, as is Mumbai and Goerli).
5. Create a new wallet
6. Get the address of the new wallet
7.  Send balance from the first wallet to the second
8. Check balance was received
- [ ] activity: settings page 
- [ ] CI: run e2e test on pipeline

### CODE REVIEW

**Comment by seabornlee** [comment]
When send balance from A to B, I got a crash.
I am not sure is that a production issue, anybody working on it?
```
    --------- beginning of crash
2021-11-21 20:58:34.845 17837-17837/io.stormbird.wallet E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.stormbird.wallet, PID: 17837
    android.view.InflateException: Binary XML file line #54 in io.stormbird.wallet:layout/dialog_action_sheet: Binary XML file line #54 in io.stormbird.wallet:layout/dialog_action_sheet: Error inflating class com.alphawallet.app.widget.BalanceDisplayWidget
    Caused by: android.view.InflateException: Binary XML file line #54 in io.stormbird.wallet:layout/dialog_action_sheet: Error inflating class com.alphawallet.app.widget.BalanceDisplayWidget
    Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:858)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1010)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
        at com.google.android.material.bottomsheet.BottomSheetDialog.wrapInBottomSheet(BottomSheetDialog.java:290)
        at com.google.android.material.bottomsheet.BottomSheetDialog.setContentView(BottomSheetDialog.java:122)
        at com.alphawallet.app.widget.ActionSheetDialog.<init>(ActionSheetDialog.java:76)
        at com.alphawallet.app.ui.SendActivity.checkConfirm(SendActivity.java:625)
        at com.alphawallet.app.ui.SendActivity.calculateTransactionCost(SendActivity.java:566)
        at com.alphawallet.app.ui.SendActivity.addressReady(SendActivity.java:548)
        at com.alphawallet.app.widget.InputAddress.ENSComplete(InputAddress.java:321)
        at com.alphawallet.app.ui.widget.entity.ENSHandler.getAddress(ENSHandler.java:117)
        at com.alphawallet.app.widget.InputAddress.getAddress(InputAddress.java:373)
        at com.alphawallet.app.ui.SendActivity.handleClick(SendActivity.java:532)
        at com.alphawallet.app.widget.FunctionButtonBar.handleStandardFunctionClick(FunctionButtonBar.java:253)
        at com.alphawallet.app.widget.FunctionButtonBar.handleAction(FunctionButtonBar.java:226)
        at com.alphawallet.app.widget.FunctionButtonBar.onClick(FunctionButtonBar.java:206)
        at android.view.View.performClick(View.java:7441)
        at android.view.View.performClickInternal(View.java:7418)
        at android.view.View.access$3700(View.java:835)
        at android.view.View$PerformClick.run(View.java:28676)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7842)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
     Caused by: android.view.InflateException: Binary XML file line #98 in io.stormbird.wallet:layout/item_balance_display: Binary XML file line #98 in io.stormbird.wallet:layout/item_balance_display: Error inflating class <unknown>
     Caused by: android.view.InflateException: Binary XML file line #98 in io.stormbird.wallet:layout/item_balance_display: Error inflating class <unknown>
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:858)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1010)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1130)
2021-11-21 20:58:34.853 17837-17837/io.stormbird.wallet E/AndroidRuntime:     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1130)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:485)
        at android.view.View.inflate(View.java:27060)
        at com.alphawallet.app.widget.BalanceDisplayWidget.<init>(BalanceDisplayWidget.java:37)
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:858)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1010)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
        at com.google.android.material.bottomsheet.BottomSheetDialog.wrapInBottomSheet(BottomSheetDialog.java:290)
        at com.google.android.material.bottomsheet.BottomSheetDialog.setContentView(BottomSheetDialog.java:122)
        at com.alphawallet.app.widget.ActionSheetDialog.<init>(ActionSheetDialog.java:76)
        at com.alphawallet.app.ui.SendActivity.checkConfirm(SendActivity.java:625)
        at com.alphawallet.app.ui.SendActivity.calculateTransactionCost(SendActivity.java:566)
        at com.alphawallet.app.ui.SendActivity.addressReady(SendActivity.java:548)
        at com.alphawallet.app.widget.InputAddress.ENSComplete(InputAddress.java:321)
        at com.alphawallet.app.ui.widget.entity.ENSHandler.getAddress(ENSHandler.java:117)
        at com.alphawallet.app.widget.InputAddress.getAddress(InputAddress.java:373)
        at com.alphawallet.app.ui.SendActivity.handleClick(SendActivity.java:532)
        at com.alphawallet.app.widget.FunctionButtonBar.handleStandardFunctionClick(FunctionButtonBar.java:253)
        at com.alphawallet.app.widget.FunctionButtonBar.handleAction(FunctionButtonBar.java:226)
        at com.alphawallet.app.widget.FunctionButtonBar.onClick(FunctionButtonBar.java:206)
        at android.view.View.performClick(View.java:7441)
        at android.view.View.performClickInternal(View.java:7418)
        at android.view.View.access$3700(View.java:835)
        at android.view.View$PerformClick.run(View.java:28676)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7842)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
     Caused by: java.lang.ClassCastException: com.alphawallet.app.widget.TokenIcon cannot be cast to android.widget.ImageView
        at com.alphawallet.app.widget.TokenIcon.<init>(TokenIcon.java:77)
        	... 50 more
```

**Comment by seabornlee** [comment]
It finally works, Hooray!!!
[e2e.gif.zip](https://github.com/AlphaWallet/alpha-wallet-android/files/7576211/e2e.gif.zip)
Need some refactor, I will do it soon.

**Comment by seabornlee** [comment]
image
@JamesSmartCell When run Espresso tests on Travis CI, the app crashed due to NPE, do you have any information about why this happening?

**Comment by seabornlee** [comment]
> image
> 
> @JamesSmartCell When run Espresso tests on Travis CI, the app crashed due to NPE, do you have any information about why this happening? Looks like it goes to SplashActivity but it went to HomeActivity when first start.

Just found you fixed it, awesome!

**Comment by JamesSmartCell** [comment]
This is why we need the test suite... I had updated an XML layout to use a different Layout type but hadn't updated where it was used in a different widget. Perhaps 1 layout definition to 1 widget is a good rule? However this triggers my 'deduplication' OCD.

**Comment by seabornlee** [comment]
> 

I thought the test failure caused by incorrect Travis configuration until get into debug mode and checked the logcat.
Yes, the e2e test can definitely detect this, and to get timely feedback, we need unit tests also.

Sometimes duplication reduces dependency is one choice, after we get the layered test suites ready, we must be more confident to refactor at any time : )

**Pull request closed without merging**
