### PR TITLE
generate trust address from tsml file

### PR DESCRIPTION
**Pull request by James-Sangalli**

### CODE REVIEW

**Comment by colourful-land** [comment]
I'm pretty close to porting that to lambda format. Wait a bit.

**Comment by colourful-land** [comment]
@James-Sangalli can you have a look at this warning "BASE64Encoder is internal proprietary API and may be removed in a future release" in your code? I thought @JamesSmartCell also used Base64 but didn't remember having the same warning.
````
/home/weiwu/IdeaProjects/alpha-wallet-android/lib/src/main/java/io/stormbird/token/tools/TrustAddressGenerator.java:26: warning: BASE64Encoder is internal proprietary API and may be removed in a future release
import sun.misc.BASE64Encoder;
````

**Comment by James-Sangalli** [comment]
@colourful-land thanks for that, build is failing on every android build atm, not related to this PR specifically...

**Comment by colourful-land** [comment]
> build is failing on every android build atm, not related to this PR specifically...

works for me:
````
lib$ gradle build
Starting a Gradle Daemon, 2 incompatible and 2 stopped Daemons could not be reused, use --status for details
Configuration on demand is an incubating feature.

BUILD SUCCESSFUL in 4s
4 actionable tasks: 4 up-to-date
````

**Comment by James-Sangalli** [comment]
> > build is failing on every android build atm, not related to this PR specifically...
> 
> works for me:
> 
> ```
> lib$ gradle build
> Starting a Gradle Daemon, 2 incompatible and 2 stopped Daemons could not be reused, use --status for details
> Configuration on demand is an incubating feature.
> 
> BUILD SUCCESSFUL in 4s
> 4 actionable tasks: 4 up-to-date
> ```

No I mean for travis, not locally.

**Comment by James-Sangalli** [comment]
@colourful-land travis is working now again, but I noticed you introduced this plugin which causes a failed build: 

> Failed to apply plugin [class 'com.github.jengelman.gradle.plugins.shadow.ShadowBasePlugin']
1973   > This version of Shadow supports Gradle 5.0+ only. Please upgrade.

Is it necessary? I will upgrade gradle

**Comment by colourful-land** [comment]
> Is it necessary? I will upgrade gradle

It works for me but that's because I use the gradle in Ubuntu which is 5.5. Interestingly, I didn't expect it to cause trouble because shadow plugin has no effect if you do gradle build (its effect is only observable if you do )

    $ gradle shadowJar

So I thought shadow plug does nothing (therefore shouldn't complain) if travis just wants to build. I blame shadow for over-extending the requirement.

You can remove it but I prefer not because you will need it to generate a zip file with dependency libraries in order to supply jar files to lambda. If you remove it, I'll add it locally every time when I want to update jar file. Which is acceptable if the trouble of upgrading gradle on travis is greater.

**Pull request merged**
