### PR TITLE
Change "paste" button to "clear" when edittext has contents

### LINKED ISSUE #2760: Paste button beside address textbox should become "Clear" if there are contents
Makes it easier to replace it

### PR DESCRIPTION
**Pull request by justindg**
- Closes #2760

### CODE REVIEW

**Review by seabornlee — COMMENTED** [review]
Nice! Let me create a unit test and you can add more cases. Let's try to keep test coverage rate growing.

**Comment by justindg** [comment]
> Nice! Let me create a unit test and you can add more cases. Let's try to keep test coverage rate growing.

Thanks @seabornlee that would be great. Also I wanted to create an E2E test but I assume we need to have #2751 merged first? I noticed it contains lots of updates regarding E2E

**Comment by seabornlee** [comment]
> > Nice! Let me create a unit test and you can add more cases. Let's try to keep test coverage rate growing.
> 
> Thanks @seabornlee that would be great. Also I wanted to create an E2E test but I assume we need to have #2751 merged first? I noticed it contains lots of updates regarding E2E. We can hold off this branch until that one is merged.

Totally agree!

**Comment by seabornlee** [comment]
@justindg You can try add more tests.

**Review by JamesSmartCell — APPROVED** [review]

**Pull request merged**
