### PR TITLE
Simplify TokensService

### PR DESCRIPTION
**Pull request by JamesSmartCell**
Fix an issue seen in crashlytics at the same time refactor the TokensService code to remove redundant code and simplify the source.

### CODE REVIEW

**Comment by James-Sangalli** [comment]
> Fix an issue seen in crashlytics at the same time refactor the TokensService code to remove redundant code and simplify the source.

James, this description is completely unclear. What issue did you fix?

**Comment by JamesSmartCell** [comment]
Issue was reported in crashlytics - so I fixed it.

While fixing the issue I realised the code could be simplified. Simplification was done.

**Comment by James-Sangalli** [comment]
@JamesSmartCell what issue?? Please make it clear, we may need to reference this some date far into the future.

**Comment by JamesSmartCell** [comment]
Crashlytics issue reported:

`TokensService.java line 401 
io.stormbird.wallet.service.TokensService.updateTokenPressure`

While fixing this I took the time to clean the code; I had previously noticed it needed cleaning and while I was fixing the issue I took the time to clean appropriately.

**Comment by James-Sangalli** [comment]
@JamesSmartCell please describe what the issue was. I would love to merge this but we need to know what it is for posterity.

**Pull request merged**
