### PR TITLE
update the Chinese strings

### PR DESCRIPTION
**Pull request by bootingman**
1. update Chinese strings and remove "Trust Wallet"
2. replace "aWallet" with "AlphaWallet" in ......./values/strings.xml
3. fix some typo

### CODE REVIEW

**Comment by James-Sangalli** [comment]
@zhangzhongnan928 @bootingman do not merge pull requests like this without first making sure it builds, this build is faulty. @bootingman add me or @JamesSmartCell or @colourful-land as reviewers.

**Comment by bootingman** [comment]
@James-Sangalli OK, I will add you as reviewer.

**Comment by James-Sangalli** [comment]
@bootingman already merged now, have to revert it first, please fix the build.

**Comment by James-Sangalli** [comment]
@bootingman we have a service that can do this anyway, no real need for it

**Pull request merged**
