### PR TITLE
Fix payment server default check

### PR DESCRIPTION
**Pull request by JamesSmartCell**
use default payment server address check.

### CODE REVIEW

**Comment by James-Sangalli** [comment]
@JamesSmartCell no idea what this PR means

**Comment by JamesSmartCell** [comment]
It's a fix to use the correct payment server URL. Previously it was wrong under certain circumstance with spawnable on currency link.

**Comment by James-Sangalli** [comment]
@JamesSmartCell for posterity please be more specific, what is the exact issue?

**Comment by JamesSmartCell** [comment]
Spawnable link wouldn't have the /api/ extension, due to old code overriding it.

The wrong API was called to check if the paymaster will fund a certain contract, so the result would always be negative - even if the contract is funded the user would have to fund the transfer.

**Pull request merged**
