### PR TITLE
History chart revisions

### LINKED ISSUE #2353: Add thin gray lines behind the chart with edge values
https://github.com/AlphaWallet/alpha-wallet-ios/issues/3418

Screenshot 2021-11-09 at 15 51 51

https://zpl.io/2jN8Yrp

Note that this is already implemented on iOS

### LINKED ISSUE #2354: Remove the shadow below the chart line
https://github.com/AlphaWallet/alpha-wallet-ios/issues/3387

### LINKED ISSUE #2355: When the price is down in last 24H, the chart should be in red color
Screenshot 2022-01-26 at 13 01 07

https://zpl.io/aNNpzGD

### PR DESCRIPTION
**Pull request by jinkjonks**
closes #2353, closes #2354 and closes #2355

### CODE REVIEW

**Comment by hboon** [comment]
@jinkjonks need to prefix every #num with the closes/fixes keyword. They keywords don't take a list. Have edited: https://github.com/AlphaWallet/alpha-wallet-android/pull/2363#issue-1116992232

**Comment by JamesSmartCell** [comment]
@jinkjonks looks good, but you need to convert the min and max into the local currency:
erc20
omg

To do this, I recommend you pass the 'currentConversionRate' from TickerService via the 'fetchHistory' call in TokenInfoFragment. Or you could try using the current ISO price symbol in the API call (less coding; you can get the ISO code from currentCurrencySymbolTxt static in TickerService) but you'll need to test it works with all the current currency codes in the wallet).

**Review by JamesSmartCell — CHANGES_REQUESTED** [review]
See the update

**Comment by jinkjonks** [comment]
image

**Review by JamesSmartCell — APPROVED** [review]

**Pull request merged**
