### PR TITLE
Add tests for showZeroBalanceToken

### PR DESCRIPTION
**Pull request by seabornlee**

### CODE REVIEW

**Comment by seabornlee** [comment]
@ChintanRathod I did some refactoring about show zero balance token, but then I found you already did it on this branch, so I just want to merge my tests to your branch. Pls review it, thx!

**Comment by JamesSmartCell** [comment]
Hi @seabornlee. Thanks for adding some more tests! we are ramping up our testing ability.

**Comment by JamesSmartCell** [comment]
Sorry pressed the wrong button, should have been just comment

**Comment by seabornlee** [comment]
What happened? Will this be merged?

**Pull request closed without merging**
