### PR TITLE
add ARTIS network https://artis.eco (untested)

### PR DESCRIPTION
**Pull request by PeterTheOne**
Website: https://artis.eco
Block explorers: https://explorer.sigma1.artis.network/ http://explorer.tau1.artis.network/
slip0044: [246529](https://github.com/satoshilabs/slips/pull/495) (sigma1) & [246785](https://github.com/satoshilabs/slips/pull/495) (tau1)
chainIds: [246529](https://github.com/lab10-coop/sigma1/blob/1881ea80b475c10765d7a763ca6afd93df005b52/spec.json#L30) (sigma1) & [246785](https://github.com/lab10-coop/tau1/blob/master/spec.json#L30) (tau1)

This code ist untested..

EthereumNetworkRepsoitory.java may be incomplete, was not sure how to fill the NetworkInfo array.

( iOS: https://github.com/AlphaWallet/alpha-wallet-ios/pull/1343 )

### CODE REVIEW

**Comment by JamesSmartCell** [comment]
Thanks, this looks good. I will test once the current sprint is complete.

**Comment by JamesSmartCell** [comment]
Hi @PeterTheOne, I am testing this PR. Can you add these lines to the PR in EthereumNetworkRepository.java as appropriate:

```
			new NetworkInfo(ARTIS_SIGMA1_NETWORK, ARTIS_SIGMA1_SYMBOL, ARTIS_SIGMA1_RPC_URL,
					"https://explorer.sigma1.artis.network/tx/",ARTIS_SIGMA1_ID, false,
					ARTIS_SIGMA1_RPC_URL,
					"https://test.explorer.sigma1.artis.network/", ETHEREUM_TICKER_NAME, ""),
			new NetworkInfo(ARTIS_TAU1_NETWORK, ARTIS_TAU1_SYMBOL, ARTIS_TAU1_RPC_URL,
					"https://explorer.tau1.artis.network/tx/",ARTIS_TAU1_ID, false,
					ARTIS_TAU1_RPC_URL,
					"https://test.explorer.tau1.artis.network/", ETHEREUM_TICKER_NAME, ""),
```

and also would you be able to send me a small amount of the base ETH of either of Sigma1 or Tau1 to this address to check everything is working?

0x4a0E9251f733Ac3908e20bdEC1852CcA8abe64c9

Thanks,

James

**Comment by PeterTheOne** [comment]
@JamesSmartCell done and send you some sigma1 ATS

**Comment by JamesSmartCell** [comment]
Thanks, I received the Artis Sigma1, and the transactions API fetch and detail view seem to be working correctly. I am unfamiliar with these networks. Do they have value or are they test nets? If they have value then is there a price ticker available anywhere? If not then I'll just use the ETH standard for now and describe them as test.

**Comment by PeterTheOne** [comment]
Thanks! :tada:

**Pull request merged**
