### PR TITLE
Address not fully populated in 'My Address' screen

### LINKED ISSUE #1619: Address not fully populated in 'My Address' screen
Last digit for the address is not populated. In the blow example, the last digit is '2' and that looks truncated. The QR code is populated accurately.

image

### PR DESCRIPTION
**Pull request by ChintanRathod**
Fixes  #1619

### CODE REVIEW

**Comment by colourful-land** [comment]
Can we simply drop the MaxWidth? You can never be sure how wide it is necessary because the user might be using a large system (accessibility option for older people)

**Comment by ChintanRathod** [comment]
> Can we simply drop the MaxWidth? You can never be sure how wide it is necessary because the user might be using a large system (accessibility option for older people)

Sure we can remove it. I just implemented to make it more visually clear.

**Comment by ChintanRathod** [comment]
@colourful-land Could you please again. I set the view properly after removing "maxwidth" property.

**Review by colourful-land — APPROVED** [review]
I assume that you tried to run it on your mobile and it works correctly there?

**Pull request merged**
