### PR TITLE
Revamp Settings Page - WIP

### PR DESCRIPTION
**Pull request by justindg**
- Added new assets
- Reworked layouts
- Added advanced settings page
- Added support settings page

Missing:
- Icon for "Manage Tokens" setting item
- Implementation for enabling/disabling biometrics/fingerprint
- Implementation for "Clear Browser Cache"
- Implementation for "Console"

### CODE REVIEW

**Comment by justindg** [comment]
@tomekalphawallet will you be able to provide an icon for the "Manage Tokens" setting? Also where do you prefer to have it placed in the Settings menu?

**Comment by tomekalphawallet** [comment]
> @tomekalphawallet will you be able to provide an icon for the "Manage Tokens" setting? Also where do you prefer to have it placed in the Settings menu?

I don't want Manage Tokens to be in the Settings menu. The link to "Add/Hide Tokens" should be in the Wallet tab, under Segmented Controls.

Screenshot 2020-03-03 16 25 14

**Comment by justindg** [comment]
> > @tomekalphawallet will you be able to provide an icon for the "Manage Tokens" setting? Also where do you prefer to have it placed in the Settings menu?
> 
> I don't want Manage Tokens to be in the Settings menu. The link to "Add/Hide Tokens" should be in the Wallet tab, under Segmented Controls.
> 
> Screenshot 2020-03-03 16 25 14

Fair enough!

**Comment by justindg** [comment]
@JamesSmartCell this ticket should be done barring any needed changes! For your review/approval.

**Comment by JamesSmartCell** [comment]
Thanks I'll check it shortly.

**Comment by JamesSmartCell** [comment]
Looks really good now, nice work @justindg

**Pull request merged**
