### PR TITLE
Stability update

### PR DESCRIPTION
**Pull request by JamesSmartCell**
Stability update from testing

### CODE REVIEW

**Comment by James-Sangalli** [comment]
@JamesSmartCell not clear what this PR is about

**Comment by JamesSmartCell** [comment]
Look at the source code

**Comment by JamesSmartCell** [comment]
It's fixes for things that are needed to be fixed.

**Comment by colourful-land** [comment]
@JamesSmartCell looking at the code, it seems rather likely the change is intended to solve a bug, but I can't see what bug it is. Is it possible for you to give the problem before giving the solution?

**Pull request closed without merging**
