### PR TITLE
Add Binance chain

### LINKED ISSUE #1584: Add Binance Smart Chain network
https://docs.binance.org/smart-chain/wallet/metamask.html
https://bscscan.com/

### PR DESCRIPTION
**Pull request by JamesSmartCell**
This PR adds Binance mainnet and test chains.

It also removes now-redundant NetworkInfo values.

Closes #1584

### CODE REVIEW

**Review by James-Sangalli — CHANGES_REQUESTED** [review]
@JamesSmartCell the non testnet chains are marked as testnet 

test

**Comment by JamesSmartCell** [comment]
> @JamesSmartCell the non testnet chains are marked as testnet
> 
> test

Unable to reproduce ...

binance

**Comment by JamesSmartCell** [comment]
Just noticed that your Eth value is also marked as 'Testnet'. Does this happen on the emulator when you do a full reset?

**Comment by James-Sangalli** [comment]
> Just noticed that your Eth value is also marked as 'Testnet'. Does this happen on the emulator when you do a full reset?

Yes, all emu

**Comment by JamesSmartCell** [comment]
Did you check build flavour? This was simplified in a previous update, ready for adding a 'China' build that has no mixpanel.

**Comment by James-Sangalli** [comment]
> Did you check build flavour? This was simplified in a previous update, ready for adding a 'China' build that has no mixpanel.

Using build variant "debug"

**Comment by JamesSmartCell** [comment]
@James-Sangalli The issues you spotted should be fixed - I rebased this PR so the fix is now in here.

**Review by James-Sangalli — APPROVED** [review]
Nice work

**Comment by Codahuy** [comment]
What name does the Binance TestNet has for file know_contract?

**Pull request merged**
